#pragma config(Motor,  port2,           frontRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           backRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           middleRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           middleLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           frontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           backLeftMotor, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(1 == 1)
  {
    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[frontRightMotor] = vexRT[Ch2];
    motor[middleRightMotor]  = vexRT[Ch2];
    motor[backRightMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[frontLeftMotor] = vexRT[Ch3];
    motor[middleLeftMotor]  = vexRT[Ch3];
    motor[backLeftMotor]  = vexRT[Ch3];
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
